// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGy_vYVxqs2-SfXqSplq2A0gHqgpgxX3A',
    appId: '1:45593094888:android:96e949d6eee0e08960f75d',
    messagingSenderId: '45593094888',
    projectId: 'pg-connect-8ce02',
    storageBucket: 'pg-connect-8ce02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqKgSJ7ykhbDWeAgKLUQ9f405yDJEy6H4',
    appId: '1:45593094888:ios:317b0bb161497e1860f75d',
    messagingSenderId: '45593094888',
    projectId: 'pg-connect-8ce02',
    storageBucket: 'pg-connect-8ce02.appspot.com',
    androidClientId: '45593094888-u8unfoqiu0jcatboi8i8ifj2qumuvhc4.apps.googleusercontent.com',
    iosClientId: '45593094888-3dn1meeg1uio4crsn4n1bsd460qd8ese.apps.googleusercontent.com',
    iosBundleId: 'com.fiyoh.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClVp4iRcNK7MRH6JfJQPtCGpK7Qi5KlNk',
    appId: '1:45593094888:web:b53987fece15016360f75d',
    messagingSenderId: '45593094888',
    projectId: 'pg-connect-8ce02',
    authDomain: 'pg-connect-8ce02.firebaseapp.com',
    storageBucket: 'pg-connect-8ce02.appspot.com',
    measurementId: 'G-BRWDT0EDXG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqKgSJ7ykhbDWeAgKLUQ9f405yDJEy6H4',
    appId: '1:45593094888:ios:701e43b1b6fa804d60f75d',
    messagingSenderId: '45593094888',
    projectId: 'pg-connect-8ce02',
    storageBucket: 'pg-connect-8ce02.appspot.com',
    androidClientId: '45593094888-u8unfoqiu0jcatboi8i8ifj2qumuvhc4.apps.googleusercontent.com',
    iosClientId: '45593094888-8fk6oer3274cn3ae0ihpmdqv34v7gb85.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClVp4iRcNK7MRH6JfJQPtCGpK7Qi5KlNk',
    appId: '1:45593094888:web:9727b937d01c06b260f75d',
    messagingSenderId: '45593094888',
    projectId: 'pg-connect-8ce02',
    authDomain: 'pg-connect-8ce02.firebaseapp.com',
    storageBucket: 'pg-connect-8ce02.appspot.com',
    measurementId: 'G-J1LQ6J2HP8',
  );

}