// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGy_vYVxqs2-SfXqSplq2A0gHqgpgxX3A',
    appId: '1:45593094888:android:f89278d99c08691460f75d',
    messagingSenderId: '45593094888',
    projectId: 'pg-connect-8ce02',
    storageBucket: 'pg-connect-8ce02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqKgSJ7ykhbDWeAgKLUQ9f405yDJEy6H4',
    appId: '1:45593094888:ios:d76017d14a8a86ba60f75d',
    messagingSenderId: '45593094888',
    projectId: 'pg-connect-8ce02',
    storageBucket: 'pg-connect-8ce02.appspot.com',
    iosClientId: '45593094888-24r7ebicvc4065cq94vt55v8pm02q9dv.apps.googleusercontent.com',
    iosBundleId: 'com.rentwise.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClVp4iRcNK7MRH6JfJQPtCGpK7Qi5KlNk',
    appId: '1:45593094888:web:cf818b0da5869b0760f75d',
    messagingSenderId: '45593094888',
    projectId: 'pg-connect-8ce02',
    authDomain: 'pg-connect-8ce02.firebaseapp.com',
    storageBucket: 'pg-connect-8ce02.appspot.com',
    measurementId: 'G-T5QD008J3L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqKgSJ7ykhbDWeAgKLUQ9f405yDJEy6H4',
    appId: '1:45593094888:ios:fe5c6e7df5d595a060f75d',
    messagingSenderId: '45593094888',
    projectId: 'pg-connect-8ce02',
    storageBucket: 'pg-connect-8ce02.appspot.com',
    iosClientId: '45593094888-8fk6oer3274cn3ae0ihpmdqv34v7gb85.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClVp4iRcNK7MRH6JfJQPtCGpK7Qi5KlNk',
    appId: '1:45593094888:web:55507451b34a094060f75d',
    messagingSenderId: '45593094888',
    projectId: 'pg-connect-8ce02',
    authDomain: 'pg-connect-8ce02.firebaseapp.com',
    storageBucket: 'pg-connect-8ce02.appspot.com',
    measurementId: 'G-MTR6CBNEDZ',
  );

}